### ISSUE TITLE
Asserts can't be disabled

### ISSUE THREAD

**Issue by vladkosi** [merryhime/dynarmic#701]
After the migration to mcl 78b4ba10c930e7bb2d9b358916467f73053d45c7 asserts are always used and can't be disabled.

Old code - https://github.com/merryhime/dynarmic/blob/ed9955891f4b276888fa91ef1b0933a47fcae155/src/dynarmic/common/assert.h
New code - https://github.com/merryhime/dynarmic/blob/master/externals/mcl/include/mcl/assert.hpp

This is the reason yuzu is crashing on Windows 7 and old versions of Windows 10 since [mainline 991](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-991).

Related yuzu bugs:
https://github.com/yuzu-emu/yuzu/issues/8247
https://github.com/yuzu-emu/yuzu/issues/8386
https://github.com/yuzu-emu/yuzu/issues/8323

**Comment by merryhime** [comment]
> This is the reason yuzu is crashing on Windows 7 and old versions of Windows 10 since [mainline 991](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-991).

I will not be allowing the ignoring of assertions unless there are performance concerns. An assertion failure is a bug that should not be ignored. Do you know the specific assertion causing this?

My assumption was the issue reference was related to aligned memory allocation hence only being compatible with newer Windows APIs, but I would be happy to know otherwise.

**Comment by vladkosi** [comment]
> Do you know the specific assertion causing this?

Seems like this one - https://github.com/merryhime/dynarmic/blob/master/src/dynarmic/backend/x64/emit_x64_memory.cpp.inc#L333

![1](https://user-images.githubusercontent.com/6567423/183670294-5c071209-9ccf-45c1-a139-8bf681d1c1e5.png)

![2](https://user-images.githubusercontent.com/6567423/183670318-2cf57eaf-54b2-40b8-8249-a84cfb29fadb.png)

This is yuzu manline 1127. Crashes on Windows 10 version 1511 and 1803.

Local build with completely removed asserts:

```
#define UNREACHABLE()
#define ASSERT(expr)
#define ASSERT_MSG(expr, ...)
#define ASSERT_FALSE(...)
#define DEBUG_ASSERT(expr)
#define DEBUG_ASSERT_MSG(expr, ...)
```
works on both.

**Comment by merryhime** [comment]
Thank you, reaching that point would mean that in the configuration provided to dynarmic, `fastmem_exclusive_access` was set to `true` in the configuration, but `fastmem_pointer` or `global_monitor` was `nullptr`, which is not a valid state to be in.

It would likely work by chance because fastmem recompilation may happen to happen with those addresses, but if an emulator VAddr happens to correspond to a valid host virtual address, this leads to Badness.

**Comment by merryhime** [comment]
See yuzu-emu/yuzu#8745.
