### ISSUE TITLE
cmake: error when building yuzu

### ISSUE THREAD

**Issue by florhizome** [merryhime/dynarmic#743]
Hey, 
still in spirit of [this](https://github.com/merryhime/dynarmic/issues/733?notification_referrer_id=NT_kwDOBReNwLM1MTk2MzIxODc5Ojg1NDI5Njk2&notifications_query=is%3Adone#event-8131917032), when I am trying to build yuzu I get this error: 

`
...

-- Configuring done
CMake Error at /gnu/store/vs9jf6p0jhgpfdq7j1yig14bd6djivr8-dynarmic-6.4.4/lib/cmake/dynarmic/dynarmicTargets.cmake:56 (set_target_properties):
  The link interface of target "dynarmic::dynarmic" contains:

    Zydis::Zydis

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /gnu/store/vs9jf6p0jhgpfdq7j1yig14bd6djivr8-dynarmic-6.4.4/lib/cmake/dynarmic/dynarmicConfig.cmake:27 (include)
  CMakeLists.txt:228 (find_package)
`
I am not sure how to interpret this means, maybe you can help? Is this even a dynarmic problem?
Btw, the earlier issue was also a problem of me using a wrong, other [mcl](http://micans.org/mcl). 
Cheers!

**Comment by FearlessTobi** [comment]
Have you tried clearing your CMake cache and then building again?

**Comment by merryhime** [comment]
Not sure why other package maintainers are not having the same issue you are, especially since most of them do unbundle packages.

Try e01a1959a39acc478d0a5d8769e47222643e2de0.

**Comment by abouvier** [comment]
This commit is wrong, none of these libraries are needed to build a program using `dynarmic`. These are private dependencies of `dynarmic`.

**Comment by merryhime** [comment]
@abouvier When building dynarmic as a shared library, surely linking to it would transitively link to dependencies?

**Comment by abouvier** [comment]
Yeah, I'm confused too :p
`fmt`, `LLVM` and `Zydis` appear to be required indeed. But not `xbyak` and `robin-map` because they are header-only libraries and not included in `dynarmic` public headers.
Also in the case of `LLVM`, the shared library (without the headers, [llvm-libs](https://archlinux.org/packages/extra/x86_64/llvm-libs/) on arch) is normally installed along `dynarmic` by the package manager. But `find_dependency(LLVM)` will require the installation of the headers ([llvm](https://archlinux.org/packages/extra/x86_64/llvm/) on arch), which is useless for the linking.

**Comment by merryhime** [comment]
@florhizome Is this still an issue?
