### ISSUE TITLE
x64: Optimization: Use host flags

### ISSUE THREAD

**Issue by merryhime** [merryhime/dynarmic#86]
Emitted code currently stores individual flags in their own host GPR registers. This is an absurd waste of registers. 

Three things should be done about this:

* Store the flags in a compact format instead of in individual registers. `sahf; seto al` is a potential candidate.
* Use existing values in host flags instead of reloading them from stored values. An instruction sequence like `add eax, 1; setc bl; bt eax, 0; adc eax, ecx` is frankly absurd.
* Move instructions that depend on flags closer to where flags are produced so that register storage becomes unnecessary.

**Tangential issue:** Semi-relatedly, the way CPSR is updated can be optimized. (For example, `pext eax, eax, 0xC101; shl eax, 28`)

**Comment by MerryMage** [comment]
A division of CPSR similar to that we’ve done with FPSCR is preferred for performance reasons. Division should likely be: 

 * CPSR.nzcv (in x64 flags format)
 * CPSR.q (boolean)
 * CPSR.ge (expanded mask format)
 * CPSR.{t,e} (speed up LocationDescriptor calculation)
 * Everything else

Note that for nzcv, nzc and v are in different bytes. It is also trivial to split nz and c since c can be independently modified with a BT instruction or similar.

**Comment by MerryMage** [comment]
Mostly implemented for both A32 and A64.

Remaining issues:

* A32: Optimization pass to replace old individual flag getters with GetNZCVFromOp where appropriate.
* A32: Introducing GetNZFromOp / some other mechanism when overwriting the full NZCV flags is not approprite.
* A64 and A32: keeping the guest flags in host flags where possible.

**Comment by MerryMage** [comment]
Partial further optimisation implemented in 8b3bc92bce6a350160b719aeebc38232b2f3a429 to load/store from JitState without conversion.

**Comment by merryhime** [comment]
Most of this is done, can consider retaining in RFLAGS in the future for longer than we currently do but code complexity in the x64 backend may not be worth it.
